name:                dhall-kubernetes
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/dhall-kubernetes#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

ghc-options:
- -Wall

default-extensions:
- DeriveDataTypeable
- DeriveGeneric
- DerivingStrategies
- DuplicateRecordFields
- GeneralizedNewtypeDeriving
- LambdaCase
- RecordWildCards
- ScopedTypeVariables
- OverloadedStrings
- FlexibleContexts
- FlexibleInstances
- ConstraintKinds
- ApplicativeDo

dependencies:
  - base >= 4.7 && < 5
  - dhall
  - aeson
  - http-conduit
  - microlens
  - text
  - containers
  - vector
  - prettyprinter
  - turtle

executables:
  dhall-kubernetes:
    source-dirs:      src
    main:             Main.hs
